bash lilybuild.sh nes/donkey-kong/01-introduction/01-introduction &&
bash lilybuild.sh nes/donkey-kong/02-game-start/02-game-start &&
bash lilybuild.sh nes/donkey-kong/03-level-start/03-level-start &&
bash lilybuild.sh nes/donkey-kong/04-level-theme-1/04-level-theme-1 &&
bash lilybuild.sh nes/donkey-kong/05-hammer/05-hammer &&
bash lilybuild.sh nes/donkey-kong/06-level-cleared/06-level-cleared &&
bash lilybuild.sh nes/donkey-kong/07-level-theme-2/07-level-theme-2 &&
bash lilybuild.sh nes/donkey-kong/08-pause/08-pause &&
bash lilybuild.sh nes/donkey-kong/09-donkey-kong-defeated/09-donkey-kong-defeated &&
bash lilybuild.sh nes/donkey-kong/10-all-levels-cleared/10-all-levels-cleared &&
bash lilybuild.sh nes/donkey-kong/11-death/11-death &&
bash lilybuild.sh nes/super-mario-bros/01-overworld/01-overworld &&
bash lilybuild.sh nes/super-mario-bros/02-underground/02-underground &&
bash lilybuild.sh nes/super-mario-bros/03-underwater/03-underwater &&
bash lilybuild.sh nes/super-mario-bros/04-castle/04-castle &&
bash lilybuild.sh nes/super-mario-bros/05-starman/05-starman &&
bash lilybuild.sh nes/super-mario-bros/06-level-cleared/06-level-cleared &&
bash lilybuild.sh nes/super-mario-bros/07-castle-cleared/07-castle-cleared &&
bash lilybuild.sh nes/super-mario-bros/08-death/08-death &&
bash lilybuild.sh nes/super-mario-bros/09-game-over/09-game-over &&
bash lilybuild.sh nes/super-mario-bros/10-hurry/10-hurry &&
bash lilybuild.sh nes/super-mario-bros/11-princess-rescued/11-princess-rescued &&
bash lilybuild.sh nes/super-mario-bros-2/01-introduction/01-introduction &&
bash lilybuild.sh nes/super-mario-bros-2/02-character-selection/02-character-selection &&
bash lilybuild.sh nes/super-mario-bros-2/03-overworld/03-overworld
