bash lilybuild.sh nes/donkey-kong/01-introduction/01-introduction &&
bash lilybuild.sh nes/donkey-kong/02-game-start/02-game-start &&
bash lilybuild.sh nes/donkey-kong/03-level-start/03-level-start &&
bash lilybuild.sh nes/donkey-kong/04-level-theme-1/04-level-theme-1 &&
bash lilybuild.sh nes/donkey-kong/05-hammer/05-hammer &&
bash lilybuild.sh nes/donkey-kong/06-level-cleared/06-level-cleared &&
bash lilybuild.sh nes/donkey-kong/07-level-theme-2/07-level-theme-2 &&
bash lilybuild.sh nes/donkey-kong/08-pause/08-pause &&
bash lilybuild.sh nes/donkey-kong/09-donkey-kong-defeated/09-donkey-kong-defeated &&
bash lilybuild.sh nes/donkey-kong/10-all-levels-cleared/10-all-levels-cleared &&
bash lilybuild.sh nes/donkey-kong/11-death/11-death &&
bash lilybuild.sh nes/super-mario-bros/01-overworld/01-overworld &&
bash lilybuild.sh nes/super-mario-bros/02-underground/02-underground &&
bash lilybuild.sh nes/super-mario-bros/03-underwater/03-underwater &&
bash lilybuild.sh nes/super-mario-bros/04-castle/04-castle &&
bash lilybuild.sh nes/super-mario-bros/05-starman/05-starman &&
bash lilybuild.sh nes/super-mario-bros/06-level-cleared/06-level-cleared &&
bash lilybuild.sh nes/super-mario-bros/07-castle-cleared/07-castle-cleared &&
bash lilybuild.sh nes/super-mario-bros/08-death/08-death &&
bash lilybuild.sh nes/super-mario-bros/09-game-over/09-game-over &&
bash lilybuild.sh nes/super-mario-bros/10-hurry/10-hurry &&
bash lilybuild.sh nes/super-mario-bros/11-princess-rescued/11-princess-rescued &&
bash lilybuild.sh nes/super-mario-bros-2/01-introduction/01-introduction &&
bash lilybuild.sh nes/super-mario-bros-2/02-character-selection/02-character-selection &&
bash lilybuild.sh nes/super-mario-bros-2/03-overworld/03-overworld &&
bash lilybuild.sh nes/super-mario-bros-2/04-underground/04-underground &&
bash lilybuild.sh nes/super-mario-bros-2/05-starman/05-starman &&
bash lilybuild.sh nes/super-mario-bros-2/06-subspace/06-subspace &&
bash lilybuild.sh nes/super-mario-bros-2/07-birdo/07-birdo &&
bash lilybuild.sh nes/super-mario-bros-2/08-fanfare/08-fanfare &&
bash lilybuild.sh nes/super-mario-bros-2/09-bonus-game/09-bonus-game &&
bash lilybuild.sh nes/super-mario-bros-2/10-death/10-death &&
bash lilybuild.sh nes/super-mario-bros-2/11-wart/11-wart &&
bash lilybuild.sh nes/super-mario-bros-2/12-boss-victory/12-boss-victory &&
bash lilybuild.sh nes/super-mario-bros-2/13-game-over/13-game-over &&
bash lilybuild.sh nes/super-mario-bros-2/14-ending/14-ending &&
bash lilybuild.sh nes/super-mario-bros-3/01-world-map-1-grass-land/01-world-map-1-grass-land &&
bash lilybuild.sh nes/super-mario-bros-3/02-world-map-2-koopahari-desert/02-world-map-2-koopahari-desert &&
bash lilybuild.sh nes/super-mario-bros-3/03-world-map-3-sea-side/03-world-map-3-sea-side &&
bash lilybuild.sh nes/super-mario-bros-3/04-world-map-4-big-island/04-world-map-4-big-island &&
bash lilybuild.sh nes/super-mario-bros-3/05-world-map-5-the-sky/05-world-map-5-the-sky &&
bash lilybuild.sh nes/super-mario-bros-3/06-world-map-6-iced-land/06-world-map-6-iced-land &&
bash lilybuild.sh nes/super-mario-bros-3/07-world-map-7-pipe-maze/07-world-map-7-pipe-maze &&
bash lilybuild.sh nes/super-mario-bros-3/08-world-map-8-dark-land/08-world-map-8-dark-land &&
bash lilybuild.sh nes/super-mario-bros-3/09-overworld-1/09-overworld-1 &&
bash lilybuild.sh nes/super-mario-bros-3/10-overworld-2/10-overworld-2 &&
bash lilybuild.sh nes/super-mario-bros-3/11-underwater/11-underwater &&
bash lilybuild.sh nes/super-mario-bros-3/12-underground/12-underground &&
bash lilybuild.sh nes/super-mario-bros-3/13-sky/13-sky &&
bash lilybuild.sh nes/super-mario-bros-3/14-starman/14-starman &&
bash lilybuild.sh nes/super-mario-bros-3/15-warp-whistle/15-warp-whistle &&
bash lilybuild.sh nes/super-mario-bros-3/16-music-box/16-music-box &&
bash lilybuild.sh nes/super-mario-bros-3/17-minigame/17-minigame &&
bash lilybuild.sh nes/super-mario-bros-3/18-toads-house/18-toads-house &&
bash lilybuild.sh nes/super-mario-bros-3/19-fortress/19-fortress &&
bash lilybuild.sh nes/super-mario-bros-3/20-miniboss-battle/20-miniboss-battle &&
bash lilybuild.sh nes/super-mario-bros-3/21-the-king-has-been-transformed/21-the-king-has-been-transformed &&
bash lilybuild.sh nes/super-mario-bros-3/22-airship/22-airship &&
bash lilybuild.sh nes/super-mario-bros-3/23-boss-battle/23-boss-battle &&
bash lilybuild.sh nes/super-mario-bros-3/24-battle-victory/24-battle-victory &&
bash lilybuild.sh nes/super-mario-bros-3/25-king-restored/25-king-restored &&
bash lilybuild.sh nes/super-mario-bros-3/26-level-cleared/26-level-cleared &&
bash lilybuild.sh nes/super-mario-bros-3/27-death/27-death &&
bash lilybuild.sh nes/super-mario-bros-3/28-game-over/28-game-over &&
bash lilybuild.sh nes/super-mario-bros-3/29-bowser-battle/29-bowser-battle &&
bash lilybuild.sh nes/super-mario-bros-3/30-ending/30-ending &&
bash lilybuild.sh nes/super-mario-bros-3/31-credits/31-credits &&
bash lilybuild.sh nes/the-legend-of-zelda/01-introduction/01-introduction &&
bash lilybuild.sh nes/the-legend-of-zelda/02-overworld/02-overworld &&
bash lilybuild.sh nes/the-legend-of-zelda/03-got-item/03-got-item &&
bash lilybuild.sh nes/the-legend-of-zelda/04-dungeon/04-dungeon &&
bash lilybuild.sh nes/the-legend-of-zelda/05-found-secret/05-found-secret &&
bash lilybuild.sh nes/the-legend-of-zelda/06-got-triforce-shard/06-got-triforce-shard &&
bash lilybuild.sh nes/the-legend-of-zelda/07-death/07-death &&
bash lilybuild.sh nes/the-legend-of-zelda/08-continue/08-continue &&
bash lilybuild.sh nes/the-legend-of-zelda/09-warp-whistle/09-warp-whistle &&
bash lilybuild.sh nes/the-legend-of-zelda/10-death-mountain/10-death-mountain
